---
kind: pipeline
name: dockerbuild

platform:
  os: linux
  arch: arm64

steps:
  - name: build_and_publish_docker
    image: plugins/docker
    settings:
      auto_tag: true
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
      insecure: true
      registry: http://docker.xps.lan
      repo: docker.xps.lan/drone-amritanshu/vault-to-env
      when:
        event:
        - push
        - tag
